name: Master

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: elisa-normal

    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build image
      run: docker build --rm -t quay.io/elisaoyj/keydb:alpine-${{ github.sha }} ./keydb/

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        check-latest: true

    - uses: azure/setup-helm@v3
    - uses: helm/chart-testing-action@v2.5.0

    - name: Lint chart
      run: ct lint --chart-dirs keydb --charts keydb --validate-maintainers=false

    - name: Create kind cluster
      uses: helm/kind-action@v1.4.0

    - name: Install required CRDs
      run: kubectl apply -f keydb/test-crds/service-monitor.yaml

    - name: Load image
      run: kind -n chart-testing load docker-image quay.io/elisaoyj/keydb:alpine-${{ github.sha }}

    - name: Install chart
      run: ct install --chart-dirs keydb --charts keydb --helm-extra-set-args "--set=topologySpreadConstraints=,imageRepository=quay.io/elisaoyj/keydb,imageTag=alpine-${{ github.sha }}"

    - name: Notify failure
      if: failure()
      env:
        MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
        MATTERMOST_TEXT: "${{ github.repository }} master build. Please check [here](${{ github.event.pull_request.html_url }}/checks)."
      run: |
        send-to-mattermost
